apiVersion: v1
kind: Pod
metadata:
  name: nginx-container
  labels:
    purpose: demonstrate-multi-container
spec:
  containers:
  - name: nginx-container
    image: nginxdemos/hello
    ports:
    - containerPort: 80